#!/bin/bash

find_todos() {
  find_result=$(git grep TODO -- './*' ':!build')
  result=$?
  if [ $result -eq 0 ]; then
    echo "TODO found in:"
    echo "$find_result" | while read -r res; do echo " - $res"; done
    exit 1
  fi
}

. ./scripts/beautifier

# putting in some fake env vars so that the prod config can be loaded
export DATABASE_URL=postgres://fake@domain.com/totally_fake
export SECRET_KEY_BASE=aTotalSecret
export LIVE_VIEW_SIGNING_SALT=fakeliveViewSigningSalt

#run_action "find_todos"
run_action "mix deps.get"
run_action "yarn --cwd assets install"
run_action "yarn --cwd assets deploy"
run_action "mix loadconfig config/prod.exs"
run_action "mix format --check-formatted"
run_action "MIX_ENV=test mix compile --warnings-as-errors --force"
run_action "mix test"
